query GetProjectFields(
    $org: String!,
    $number: Int!,
  	$first:Int!,
  	$endCursor:String,
  ){
  {{owner}}(login: $org) {
    projectV2(number: $number) {
      fields(first: $first, after: $endCursor) {
        totalCount
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
           ... on ProjectV2FieldCommon {
              dataType
              name
              id
            }
           ... on ProjectV2SingleSelectField {
            options {
              name
              id
            }
          }
        }
      }
    }
  }
}