query GetIssues($filters: String!, $first: Int!, $cursor: String) {
  search(query: $filters, type: ISSUE, first: $first, after: $cursor) {
    totalCount: issueCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ... on Issue {
        id
        url
        title
        createdAt
        updatedAt
        repository {
          url
        }
        assignees(first: 10) {
          nodes {
            login
          }
        }
        labels(first: 100) {
          nodes {
            name
            url
          }
        }
        # linkedIssues: timelineItems(first:100, itemTypes:CROSS_REFERENCED_EVENT){
        #   nodes{
        #     ... on CrossReferencedEvent {
        #       willCloseTarget
        #       source {
        #         ... on Issue {
        #           number
        #           url
        #         }
        #         ... on PullRequest {
        #           number
        #           url
        #         }
        #       }
        #     }
        #   }
        # }
      }
    }
  }
}